export const ADD_FOOD = "ADD_FOOD"
export const GET_ALL_FOOD = "GET_ALL_FOOD"
export const SET_CUR_POST = "SET_CUR_POST"
export const FOOD_LENGTH = "FOOD_LENGTH"
export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
